### ISSUE TITLE
chip support

### ISSUE THREAD

**Issue by ZeroChaos-** [aircrack-ng/rtl8812au#157]
in dkms.conf you "make" and the "make 8814=1" or whatever, but in the makefile you have 8814=1 set 8812, 8814, and 8821 support.  meaning, what is the point of building 8812au.ko when support for the same chip is built into 8814au.ko?

**Comment by ZeroChaos-** [comment]
this is probably dupe of 158, but I'll let you close it once you see both in case I'm wrong.

**Comment by kimocoder** [comment]
You will need them all enabled in order to build the 8814au, it's just the way they were linked.
This is different from the v5.1.5 code, where they are seperated.

8812/8821au uses the same HAL, so they're always been a part of each other, while 8814au got it's own HAL again. Just a note.

Pros/cons of having them linked.. really don't know yet as it's the work of @fariouche
All I know is that they all is tested working, it's just the switches that have changed + they all get registered under "rtl8812au" in airmon-ng instead of rtl8812au and 8814au.

**Comment by kimocoder** [comment]
#158 is more detailed on the issue. I've given this a tought also, the correct way to correct this segfault would be to divide them into 2 seperated, the 8812/8821 should be linked, while 8814au should be standalone, just like the v5.1.5 branch.

Could this be done @fariouche ?

The correct way should be..
CONFIG_RTL8812A = y
CONFIG_RTL8821A = y
to compile the 8812au with 8821au support

while for 8814au support, the config should be
CONFIG_RTL8812A = n
CONFIG_RTL8821A = n
CONFIG_RTL8814A = y

then the segfault from #158 should be fixed

**Comment by fariouche** [comment]
I've merge the HAL (a very small portion by the way, that is fonctionnaly equivalent) so that we can build only one driver to support all chipsets.
There is everything inside to replace the ifdef by if() conditions.
However, the module file name is not correct (the makefile is a bit stupid) and uses the latest name in the list of supported chipset, while the name registered in the kernel is still 8812au.

And the separate config as described above should make the driver behave exactly as before (only one chip per module)
The crash in #158 is most likely something else

**Comment by fariouche** [comment]
sory haven't look close enough on the crash dump. so it's because the driver reports 8812au as its name, clashing with the 8812au.ko already inserted?
The idea is to only use the 8814au.ko for all chips (and maybe rename the ko and driver name by the way)

**Comment by kimocoder** [comment]
The idea is good in itself, i support that. It kinda works now, but a segfault is bad anyway.
Don't even know if it may be done without the kernel goes panic mode.

Cons would be the actuall panic/segfault and driver reporting wrong chipset detection though

**Comment by ZeroChaos-** [comment]
if the intent is to support all chips with one driver, then probably update dkms.conf and maybe pick a generic module name?

**Comment by kimocoder** [comment]
The dkms.conf needs an update, yes. I'll do it soon enough
