### ISSUE TITLE
Deauth is not working and dumping packets with no eapol 

### ISSUE THREAD

**Issue by barakat-abweh** [aircrack-ng/rtl8812au#367]
driver not working properly with aircrack and its tool, it works using different adapters so i think the problem is related to driver

**Comment by azamet90** [comment]
same on me but if i install the driver from kali repo works fine but then the wifi signal range is poor

**Comment by kimocoder** [comment]
@barakat-abweh @azamet90 

Kali has v5.2.20(.2), that one struggles with range (phydm issue related to power), but that has been fixed in v5.6.4.2.

and it works in airmon-ng, wifite2 and hcxtools.. so try a newer branch, it won't be pushed before a month or so. This issue should be resolved by upgrading. Thanks!

![injection](https://user-images.githubusercontent.com/4252297/68883152-bd003500-0710-11ea-9d2d-85d920ed71f6.png)
