### ISSUE TITLE
Installation in chroot environment

### ISSUE THREAD

**Issue by seppzer0** [aircrack-ng/rtl8812au#397]
I've successfully installed the driver on my main amd64 machine - everything works flawlessly - but still can't figure out why it won't work in my aarch64 chroot environment.

I know that the problem is that I don't have the kernel sources in my chroot linux. But as far as I've noticed android kernel sources are a bit different compared to linux. 

I know where to find the sources of the custom kernel I use. I just don't know which files and folders I need from the repo to successfully install the driver.

Help much appreciated

**Comment by nvixonimo** [comment]
Answered to every open issue near mine but still ignoring this one. I guess that's how much of a smartboy you are not helping newbies in development. Sad, really. I did seek for guidance, because even googling did not help at the end.

Good thing not every developer is like this and someone did help. 
On another repo. With this project.

Good luck

**Comment by ziyaniftaliev** [comment]
Hi. Can you tell me how to build the ALFA AWUS036ACH (RTL8812AU) driver for a Xiaomi Mi A3 running Android 11 LineageOS 18.1 with the official Kali Nethunter custom kernel?
