### ISSUE TITLE
Upstream the driver

### ISSUE THREAD

**Issue by FFY00** [aircrack-ng/rtl8812au#703]
Hello, has there been any thought about upstreaming this driver? It would be very helpful for users. Are there any reasons this hasn't happened yet?

Cheers,
Filipe

**Comment by kimocoder** [comment]
No, Realtek is working on a newer driver, named "RTW88", rtl8812au will find it's way over there, with time..

**Comment by benpicco** [comment]
Looks like only rtl8822**b**[e|u] and newer made it into `rtw88`, the A series chips that this driver supports were left out.

Has someone already figured out how big the difference between rtl8812a and rtl8822b were - or maybe it's closer to rtl8192eu which is supported by `rtl8xxxu` :thinking: (since they are part of the same [windows driver](https://www.realtek.com/en/component/zoo/category/rtl8812au-software)).
