### ISSUE TITLE
airodump-ng  "lenght 0 "  

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/rtl8812au#724]

**Comment by Mister-X-** [comment]
Could you post a PCAP with just of the beacons from that network?

**Comment by slt90** [comment]
> Could you post a PCAP with just of the beacons from that network?

Hi Mister-X, sorry for the duplicate posts,I find this problem with a lot of wireless networks (I assume only 802.11ac networks) 

Here is the pcap file with a client connected to the network.
Thanks.

[testnetwork.pcap-01.zip](https://github.com/aircrack-ng/rtl8812au/files/5250823/testnetwork.pcap-01.zip)

**Comment by Mister-X-** [comment]
The SSID isn't advertised. There is no SSID IE in the beacon at all.

**Comment by slt90** [comment]
> The SSID isn't advertised. There is no SSID IE in the beacon at all.



> The SSID isn't advertised. There is no SSID IE in the beacon at all.

it happens to me only with 802.11 ac networks the name of this network and "test" as you can see from the photo it does not even find essid other networks

**Comment by Mister-X-** [comment]
There is no "test" SSID on the picture. The -1 (channel) have been explained multiple times in the forum, and these are because a station sent a frame to an access point that is too far away from us (like a data frame, probe, whatever), and airodump-ng found a BSSID in the frame that isn't in its list, and shows it. We cannot be 100% sure of the channel or the rate of the network, unless it is coming from the AP itself.

Upload a SINGLE beacon for the other networks so I can tell what is wrong. So far, this isn't a bug in airodump-ng. It could very well be a custom implementation in ubiquiti stuff that make it look like it's broadcasting SSID.

**Comment by slt90** [comment]
attached some beacon files, however I detect the problem only with AC networks.

[Network.zip](https://github.com/aircrack-ng/rtl8812au/files/5251376/Network.zip)

**Comment by Mister-X-** [comment]
- ubnt-ultra SSID which has a tp-link MAC is a 802.11n network
- Ubiquiti MAC ending with 6c:93:23  5a:d8:7e are 802.11ac, no SSID IE in beacon (same as the one your posted initially
- Ubiquiti MAC ending with de:0e:eb is 802.11g, with UBNT ssid
- Ubiquiti MAC ending with 76:d4:49 is 802.11n, with hidden SSID IE

All the 802.11ac AP are ubiquiti. And as a matter of fact, all the beacons in these PCAP come from ubiquiti APs

It is now even more likely a custom implementation from ubiquiti, and not a bug. Unless you can show me it happens with a lot of other 802.11ac networks (that aren't ubiquiti), case closed.

**Comment by slt90** [comment]
can you add this ubiquiti customization to aircrack suite?
Thanks.

**Comment by aircrack-ng** [comment]
If you can provide the information requested in aircrack-ng/aircrack-ng#2187
