### ISSUE TITLE
AWUS036ACM Extremely poor range

### ISSUE THREAD

**Issue by deanfourie1** [aircrack-ng/rtl8812au#895]
I just purchased a AWUS036ACM, and im getting extremely poor rage. Can anyone suggest the best driver to use with this adapter? Is it the 8812au driver?

I cannot scan networks past the range of my own house.

Thanks in advance.

**Comment by morrownr** [comment]
The ACM uses a mt7612u chipset. Current mainstream distros have this driver in-kernel. I keep a repo with information about this chipset:

https://github.com/morrownr/7612u

I have an ACM. I have not noted problems with range. I would rate it as slightly above average for range. I also have an ACHM and it has the longest range of any dual band adapter I have used, to include having longer range than the ACH.

Be glad to help if I can but the discussion should probably be taken to the repo I listed above since this repo is about 8812au chipsets. Regards.

**Comment by morrownr** [comment]
Here is a link that shows performance testing regarding the statement above:

https://github.com/morrownr/USB-WiFi/blob/main/Performance_Comparison.md

**Comment by kimboslice99** [comment]
> Here is a link that shows performance testing regarding the statement above:
> 
> https://github.com/morrownr/USB-WiFi/blob/main/Performance_Comparison.md

Don't mean to necro, but what happened to this perf comparison

**Comment by morrownr** [comment]
It is in the home folder at this location:

https://github.com/morrownr/USB-WiFi

If interested in a speed test, go to the same repo and look for issue 139.

Regards
