### ISSUE TITLE
problem in monitor mode

### ISSUE THREAD

**Issue by lsy512** [aircrack-ng/rtl8812au#958]
hi,i am using this driver on ubuntu. after make install ,i do these steps to let rtl8812 in monitor mode

sudo ifconfig wlx74da381f48f7 down
sudo iwconfig wlx74da381f48f7 mode monitor
sudo ifconfig wlx74da381f48f7 up
sudo iwconfig wlx74da381f48f7 channel 4

then,i use tcpdump to moniter data
sudo tcpdump -i wlx74da381f48f7
i fount data is from different channel

![image](https://user-images.githubusercontent.com/8577570/164958359-763779b9-0615-4dd2-b99f-e4f8c685bfd8.png)
![image](https://user-images.githubusercontent.com/8577570/164958373-440a5ad2-0b14-43e0-ae37-ba10a82c68e1.png)

i have set channel to 4.why i can receive data from other channal ?
can you help me to solve this problem?
thanks

**Comment by ZerBea** [comment]
This will explain why you got traffic from the neighbor channels::
https://witestlab.poly.edu/blog/ieee-802-11-wlans-using-partially-overlapped-channels/
https://www.speedguide.net/faq/wireless-channels-overlap-261
https://serverfault.com/questions/152920/what-happens-when-wifi-channels-overlap
and a lot of pictures here:
https://duckduckgo.com/?q=WiFI+overlapped+channels&t=ffab&iax=images&ia=images

This will explain why you receive traffic from channel 1:
In addition to that, it take a while until the channel is set. Up to this time, you receive traffic from the initial channel.

This will explain what happens if you haven't stopped NetworkManager. In that case you will receive traffic from all channels, regardless what you have set, because NetworkManager hops on all channels.
"Stop all services which take access to the physical interface (NetworkManager, wpa_supplicant,...)"
https://github.com/ZerBea/hcxdumptool/blob/master/README.md


BTW:
iwconfig (use ioctl system calls) and ipconfig are deprecated and replaced by iw (use NETLINK) and ip.
https://www.tecmint.com/deprecated-linux-networking-commands-and-their-replacements/

Most of the Realtek drivers (especially rtl8812au) highly depend on NETLINK, so it is recommended to use iw here.

```
$ sudo systemctl stop NetworkManager.service
$ sudo systemctl stop wpa_supplicant.service
$ sudo ip link set $WLANDEV down
$ sudo iw dev $WLANDEV set type monitor
$ sudo ip link set $WLANDEV up
$ sudo iw dev $WLANDEV info
```
where WLANDEV is the name of your wlan interface.

**Comment by lsy512** [comment]
Thanks for your help, it worked fine after I closed the wpa_supplicant program

**Comment by ZerBea** [comment]
You're welcome. tcpdump is not able to notice that another tool change the channel. That caused that you received traffic from other channels set by the other tool.
Please close this issue, because it isn't related to the driver.

**Comment by lsy512** [comment]
I tested again today and found a very strange problem.
I use a rtl8812 network card for data injection. Another RTL8812AU for data packet capture.
My test method is as follows：
1 inject data at greater than 5mbps on the transmitter side
2 Use the command tcpdump -i wlan -c 2000 to receive data to verify the data reception rate
In this case, I test that it takes about 15-20s to receive 2000 packets, which is obviously inconsistent with the injection rate.

Without finding the source of the problem, I guessed that it was a receiving problem, so I used another rt3070 to receive on the same device. It takes about 4-5s to receive 2000 packets. According to calculations this is about 5mbps.
At this time, I switched to the original rtl8812au for data reception on this device, and found that it only took 4-5s for the rtl8812 network card to receive 2000 data packets.

After repeated tests, I found that after removing the rt3070 network card, it takes 15-20s for the rtl8812 network card to receive 2000 packets, but after inserting the RT3070 and setting it to monitor mode. Then use rtl8812au for data reception, it only takes 4-5s at this time.
This is a strange problem, is it a system problem or a driver problem? 
thanks
